config_setting(
    name = "develop",
    values = {
        "define": "environment=develop",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "production",
    values = { 
        "define": "environment=production",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "adhoc",
    values = { 
        "define": "environment=adhoc",
    },
    visibility = ["//visibility:public"],
)